---
name: Ruby LSP bug
description: File a bug report about the VS Code Ruby LSP extension
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: >
        Thank you for filing a bug report! Please answer the following questions to help us understand the issue.
  - type: input
    attributes:
      label: Operating System
      description: The operating system where this issue occurs
    validations:
      required: true
  - type: input
    attributes:
      label: Ruby version
      description: The Ruby version being used to run the LSP
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Project has a bundle
      description: The project where the Ruby LSP is being used has a Gemfile.lock
      options:
        - label: Has bundle
  - type: dropdown
    attributes:
      label: Ruby version manager being used
      description: How Ruby was installed on your system and how you select Ruby versions
      options:
        - asdf
        - chruby
        - no manager
        - rbenv
        - rvm
        - shadowenv
        - other (please specify in description)
    validations:
      required: true
- type: checkboxes
  attributes:
    options:
      - label: I have followed the instructions on
        [troubleshotting](https://github.com/Shopify/vscode-ruby-lsp/blob/main/TROUBLESHOOTING.md)
      - label: I am on the latest version of the Ruby LSP VS Code extension
      - label: I am on the latest version of the Ruby LSP server gem
      - label: I am on the latest version of VS Code
- type: textarea
  attributes:
    label: Description
    description: Reproduction steps and an explanation of the observed behavior
    validations:
      required: true
