version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: weekly
    reviewers:
      - "Shopify/ruby-dev-exp"
    ignore:
      - dependency-name: "@types/vscode"
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
