name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        uses: actions/setup-node@v2
        with:
          node-version: "17"
          cache: "yarn"

      - name: 📦 Install dependencies
        run: yarn --frozen-lockfile

      - run: yarn run lint

      - run: /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      - run: yarn run test
        env:
          DISPLAY: ":99.0"
