name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      - name: 📦 Install dependencies
        run: yarn --frozen-lockfile

      - name: Lint
        run: yarn run lint

  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "yarn"

      # We need some Ruby installed for the environment activation tests. The Ruby version installed here needs to match
      # the one we're using the ruby.test.ts file
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"

      # On GitHub actions, the Ruby binary is installed in a path that's not really standard for version managers. We
      # create a symlink using a standard path so that we test the same behaviour as in development machines
      - name: Symlink Ruby on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          mkdir /opt/rubies
          ln -s /opt/hostedtoolcache/Ruby/3.2.2/x64 /opt/rubies/3.2.2

      - name: Symlink Ruby on MacOS
        if: matrix.os == 'macos-latest'
        run: |
          mkdir /Users/runner/.rubies
          ln -s /Users/runner/hostedtoolcache/Ruby/3.2.2/x64 /Users/runner/.rubies/3.2.2

      - name: Symlink Ruby on Windows
        if: matrix.os == 'windows-latest'
        run: |
          New-Item -Path C:\Ruby32-x64 -ItemType SymbolicLink -Value C:\hostedtoolcache\windows\Ruby\3.2.2\x64

      - name: 📦 Install dependencies
        run: yarn --frozen-lockfile

      - run: /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      - run: yarn run test
        env:
          DISPLAY: ":99.0"
