name: Release

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions/setup-node@v2
        name: Use Node.js 17.x
        with:
          node-version: "17"
          cache: "yarn"

      - name: 📦 Install dependencies
        run: yarn --frozen-lockfile

      - name: 🔨 Package
        run: yarn run package

      - name: Publish extension in the marketplace
        run: node_modules/.bin/vsce publish --packagePath vscode-ruby-lsp.vsix
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
