name: Publish

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - uses: actions/setup-node@v3
        name: Use Node.js 18.x
        with:
          node-version: "18"
          cache: "yarn"

      - name: 📦 Install dependencies
        run: yarn --frozen-lockfile

      - name: Create CHANGELOG.md
        run: |
          RELEASE_NOTES=$(curl -L https://api.github.com/repos/Shopify/vscode-ruby-lsp/releases)
          CHANGELOG=$(echo "$RELEASE_NOTES" | jq -r '.[] | "# \(.tag_name)", .body')
          printf "%s\n" "$CHANGELOG" > CHANGELOG.md

      # Stable releases
      - name: Publish extension in the marketplace
        if: "!github.event.release.prerelease"
        run: |
          yarn run package
          node_modules/.bin/vsce publish --packagePath vscode-ruby-lsp.vsix
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      # Prereleases
      - name: Package and publish prerelease extension in the marketplace
        if: "github.event.release.prerelease"
        run: |
          yarn run package_prerelease
          node_modules/.bin/vsce publish --pre-release --packagePath vscode-ruby-lsp.vsix
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
