name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "The version to be released in the format X.Y.Z"
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - name: Release
        uses: actions/github-script@v6
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            const { data } = await github.rest.repos.getContent({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: "package.json",
            });

            const decoded = Buffer.from(data.content, "base64").toString("ascii");
            const updated = decoded.replace(/\"version\":.*,/, `"version": "${{ inputs.version }}",`);

            const response = await github.rest.repos.createOrUpdateFileContents({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: "package.json",
              message: `Bump version to v${{ inputs.version }}`,
              content: Buffer.from(updated).toString("base64"),
              "committer.name": "github-actions",
              "committer.email": "github-actions@github.com",
              sha: data.sha,
              branch: "test-action-group-pairing"
            })

            await github.rest.git.createTag({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag: `v${{ inputs.version }}`,
              message: `v${{ inputs.version }}`,
              object: response.data.commit.tree.sha,
              type: "commit",
              "tagger.name": "github-actions",
              "tagger.email": "github-actions@github.com"
            })

            /*
            await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: "refs/tags/v${{ inputs.version }}",
              name: "v${{ inputs.version }}",
              generate_release_notes: true
            })
            */
